[project]
name = "rpd-hub-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.11.0",
    "pandas>=2.3.3",
    "psycopg>=3.2.13",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.44",
]
